using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using System.IO;

namespace BlackBoxAnalizer
{
    public partial class mainForm : Form
    {
        string str;
        string fileName = @"C:\Documents and Settings\nima\Desktop\PAL\Scanned files\n.txt";
        Analizer analizer;
        public mainForm()
        {
            InitializeComponent();
            FileNameLbl.Text = fileName;

            getResult();
            resultLbl.Text = str;
        }

        private void ImportFileBtn_Click(object sender, EventArgs e)
        {
            openFileDialog1.FileName = fileName;
            openFileDialog1.Filter = "txt files (*.txt)|*.txt|All files (*.*)|*.*";
            openFileDialog1.RestoreDirectory = true;

            if (openFileDialog1.ShowDialog() == DialogResult.OK)
            {
                fileName = openFileDialog1.FileName;
                FileNameLbl.Text = fileName;
                SaveBtn.Visible = false;
            }

            getResult();
            resultLbl.Text = str;
        }

        void getResult()
        {
            if (!File.Exists(fileName))
            {
                MessageBox.Show(fileName + " does not exist.");
            }

            using (StreamReader sr = File.OpenText(fileName))
            {
                analizer = new Analizer();
                if (!analizer.Parse(sr))
                {
                    MessageBox.Show("Invalid file.\nThe selected file is not for this use.\nPlease be sure the file is generated by the PEEL Scanner kit.", "Error");
                }
            }

            str = analizer.GetResult();

        }

        private void SaveBtn_Click(object sender, EventArgs e)
        {
            Stream stream;

            saveFileDialog1.FileName = fileName.TrimEnd(".txt".ToCharArray()) + " result.txt";
            saveFileDialog1.Filter = "txt files (*.txt)|*.txt|All files (*.*)|*.*";
            saveFileDialog1.RestoreDirectory = true;

            if (saveFileDialog1.ShowDialog() == DialogResult.OK)
            {
                if ((stream = saveFileDialog1.OpenFile()) != null)
                {
                    StreamWriter streamWriter = new StreamWriter(stream);
                    streamWriter.Write(str);
                    streamWriter.Close();
                    stream.Close();
                }
            }
        }

        private void CloseBtn_Click(object sender, EventArgs e)
        {
            this.Close();
        }
    }
}
